version: "3"

services:
  nginx:
   image: elestio/nginx-auto-ssl
   container_name: build-guardian-nginx
   volumes:
     - build-guardian-data:/var/www/build-guardian
     - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
     - ./logs:/var/log/nginx
   ports:
     - "80:80"
     - "443:443"
   depends_on:
     - build-guardian
   environment:
    DOMAINS: '143.198.25.9'  # Cambia por la IP del servidor si es necesario

  build-guardian:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: build-guardian
    restart: unless-stopped
    volumes:
     - build-guardian-data:/var/www/build-guardian
    depends_on:
      - mongo

  db:
    image: mysql:8.0
    container_name: build-guardian-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: build-guardian
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql

  mongo:
    image: mongo:latest
    container_name: app-mongo
    restart: unless-stopped
    tty: true
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db

volumes:
  dbdata:
    driver: local
  build-guardian-data:
    driver: local
  mongodata:
    driver: local
